learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views
app_name ='basic_app'
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import url,include
urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'special/',views.special,name='special'),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    def __str__(self):
        #username is the default attribute of User
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('username','email','password')
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserProfileInfoForm,UserForm
from django.urls import reverse
#decorator:if you want a view require user login, you can decorator it with login_required
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse("YOU ARE logged in, NICE")

@login_required
def user_logout(request):
    #builtin func automatically logout user
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    #aassume first user not registered
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            #save directed to database
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            #make sure set up one to one relationship
            #to prevent overide the user
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form=UserProfileInfoForm()
        #registered = True
    return render(request,'basic_app/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})


#new view, make sure views跟import的东西不重名
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)
    
        if user:
            if user.is_active:
                login(request,user)
                #redirect to home page
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("account not active!")
        else:
            print("hi, someone try to login but failed")
            print("Username:{} and password{}".format(username,password))
            return HttpResponse("invalid login")
    else:
        return render(request,'basic_app/login.html',{})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
<div class='container'>
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="{% url 'index' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'admin:index' %}">Admin <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'basic_app:register' %}">Register</a>

    {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a class="nav-item nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
    {% endif %}
      <a class="nav-item nav-link" href="#">Pricing</a>
      <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
    </div>
  </div>
</div>
{% comment %} </nav>
<nav class='navbar navbar-default navbar-static-top'>
    <div class='container'>
        <ul class='nav navbar-nav'>
          <li><a class='navbar-brand' href="{% url 'index' %}">DJANGO</a></li>
          <li><a class='navbar-link' href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class='navbar-link' href="{% url 'basic_app:register' %}">Register</a></li>
        </ul>
    </div>
</nav> {% endcomment %}
    <div class='container'>
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<p></p>
<div class='container'>
    <div class='jumbotron'>
        <h1>Django level five</h1>
    </div>
</div>
{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html'%}
{% block body_block %}
<div class='jumbotron'>
    <h1>please login</h1>
    <form action="{% url 'basic_app:user_login' %}" method='POST'>
        {% comment %} 有form就要加csrf_token {% endcomment %}
        {% csrf_token %}
        <label for='username'>Username:</label>
        <input type='text' name='username' placeholder='enter username'>
        <label for='password'>Password:</label>
        <input type='password' name='password' placeholder='enter password'>

        <input type='submit' name='' value='login'>
    </form>
</div>
{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}
<div class='jumbotron'>
    {% if registered %}
        <h1>thank you for register</h1>
    {% else %}
        <h1>register here</h1>
        <h3>fill out the form:</h3>
    {% comment %} make sure you have enctype,otherwise your image won't work {% endcomment %}
    <form enctype='multipart/form-data' method='post'>
        {% csrf_token %} 
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name='' value='register'>
    </form>
    {% endif %}
</div>
{% endblock %}